import dayjs from '../../utils/dayjs';

import { QueryInterface } from 'sequelize';

export const up = async ({ context: queryInterface }: { context: QueryInterface }) => {
    await queryInterface.bulkInsert(
        'matches',
        [
            {
                id: 1,
                initial: 3,
                challengerId: 2,
                acceptorId: 1,
                winner: 2,
                score: '6-2 6-4',
                challengerElo: 370,
                acceptorElo: 365,
                challengerEloChange: 33,
                acceptorEloChange: -33,
                challengerMatches: 1,
                acceptorMatches: 1,
                challengerRank: 1,
                acceptorRank: 1,
                challengerPoints: 23,
                acceptorPoints: 6,
                comment: 'That was an awesome match',
                youtube: 'some',
                playedAt: dayjs.tz().subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                acceptedAt: dayjs.tz().subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                same: '',
                stat: JSON.stringify({
                    timeTotal: 173,
                    challenger: {
                        forehandWinners: 10,
                        backhandWinners: 6,
                        serveWinners: 0,
                        forehandUnforced: 22,
                        backhandUnforced: 12,
                        serveUnforced: 2,
                        forehandForced: 11,
                        backhandForced: 9,
                        serveTotal: 79,
                        firstServeIn: 62,
                        firstServeWon: 37,
                        secondServeWon: 8,
                        breakpointsTotal: 10,
                        breakpointsWon: 6,
                    },
                    acceptor: {
                        forehandWinners: 6,
                        backhandWinners: 0,
                        serveWinners: 0,
                        forehandUnforced: 17,
                        backhandUnforced: 8,
                        serveUnforced: 3,
                        forehandForced: 19,
                        backhandForced: 15,
                        serveTotal: 61,
                        firstServeIn: 36,
                        firstServeWon: 19,
                        secondServeWon: 9,
                        breakpointsTotal: 12,
                        breakpointsWon: 3,
                    },
                }),
            },
            {
                id: 2,
                initial: 3,
                challengerId: 2,
                acceptorId: 3,
                winner: 3,
                score: '5-7 2-6',
                challengerElo: 360,
                acceptorElo: 365,
                challengerEloChange: -36,
                acceptorEloChange: -36,
                challengerMatches: 2,
                acceptorMatches: 1,
                challengerRank: 1,
                acceptorRank: 3,
                challengerPoints: 9,
                acceptorPoints: 21,
                youtube: 'some',
                playedAt: '2021-05-02 08:10:47',
                acceptedAt: dayjs.tz().subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                same: '',
            },
            {
                id: 3,
                initial: 3,
                challengerId: 2,
                acceptorId: 4,
                winner: 2,
                score: '6-7 6-2 7-5',
                challengerElo: 355,
                acceptorElo: 375,
                challengerEloChange: 30,
                acceptorEloChange: -30,
                challengerMatches: 3,
                acceptorMatches: 1,
                challengerRank: 1,
                acceptorRank: 4,
                challengerPoints: 18,
                acceptorPoints: 10,
                youtube: 'some',
                playedAt: '2021-05-03 12:10:47',
                acceptedAt: dayjs.tz().subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                same: '',
            },
            {
                id: 4,
                initial: 3,
                challengerId: 1,
                acceptorId: 3,
                winner: 1,
                score: '6-7 7-6 1-0',
                challengerElo: 360,
                acceptorElo: 365,
                challengerEloChange: 32,
                acceptorEloChange: -32,
                challengerMatches: 3,
                acceptorMatches: 2,
                challengerRank: 2,
                acceptorRank: 3,
                challengerPoints: 19,
                acceptorPoints: 10,
                playedAt: '2021-05-04 14:22:47',
                acceptedAt: dayjs.tz().subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                same: '',
            },
            {
                id: 5,
                initial: 3,
                challengerId: 3,
                acceptorId: 4,
                winner: 4,
                score: '3-6 0-6',
                challengerElo: 360,
                acceptorElo: 365,
                challengerEloChange: -36,
                acceptorEloChange: 36,
                challengerMatches: 3,
                acceptorMatches: 2,
                challengerRank: 3,
                acceptorRank: 4,
                challengerPoints: 5,
                acceptorPoints: 24,
                playedAt: '2021-05-15 15:30:47',
                acceptedAt: dayjs.tz().subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                same: '',
            },
            {
                id: 61,
                initial: 3,
                challengerId: 17,
                acceptorId: 18,
                winner: 17,
                score: '6-2 6-4',
                challengerElo: 370,
                acceptorElo: 365,
                challengerEloChange: 33,
                acceptorEloChange: -33,
                challengerMatches: 1,
                acceptorMatches: 1,
                challengerRank: 1,
                acceptorRank: 1,
                challengerPoints: 23,
                acceptorPoints: 6,
                comment: '',
                playedAt: dayjs.tz().subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                acceptedAt: dayjs.tz().subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                same: '',
            },
        ],
        {}
    );

    // Proposals
    await queryInterface.bulkInsert(
        'matches',
        [
            {
                id: 6,
                initial: 1,
                challengerId: 3,
                acceptorId: null,
                challengerRank: 5,
                acceptorRank: null,
                challengerPoints: null,
                acceptorPoints: null,
                acceptedAt: null,
                place: 'Pullen, Kentwood',
                comment: 'Time and place flexible',
                playedAt: dayjs.tz().add(2, 'day').add(1, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                createdAt: '2021-05-05 14:22:47',
                winner: null,
                score: null,
                same: '',
                isProposalSent: 1,
            },
            {
                id: 7,
                initial: 1,
                challengerId: 2,
                acceptorId: null,
                challengerRank: 5,
                acceptorRank: null,
                challengerPoints: null,
                acceptorPoints: null,
                acceptedAt: null,
                place: 'Millbrook',
                comment: '',
                playedAt: dayjs.tz().add(2, 'day').add(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                createdAt: '2021-05-03 11:00:00',
                winner: null,
                score: null,
                same: '',
                isProposalSent: 1,
            },
            {
                id: 31,
                initial: 1,
                challengerId: 2,
                acceptorId: null,
                challengerRank: 5,
                acceptorRank: null,
                challengerPoints: null,
                acceptorPoints: null,
                acceptedAt: null,
                place: 'Lions',
                comment: '',
                playedAt: dayjs.tz().subtract(2, 'week').format('YYYY-MM-DD HH:mm:ss'),
                createdAt: '2021-05-03 11:00:00',
                winner: null,
                score: null,
                same: '',
                isProposalSent: 1,
            },
            {
                id: 22,
                initial: 1,
                challengerId: 6,
                acceptorId: null,
                challengerRank: 5,
                acceptorRank: null,
                challengerPoints: null,
                acceptorPoints: null,
                acceptedAt: null,
                place: 'Millbrook',
                comment: '',
                playedAt: dayjs.tz().add(2, 'day').add(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                createdAt: '2021-05-03 11:00:00',
                winner: null,
                score: null,
                same: '',
                isProposalSent: 1,
            },
            {
                id: 40,
                initial: 1,
                challengerId: 1,
                acceptorId: null,
                challengerRank: 5,
                acceptorRank: null,
                challengerPoints: null,
                acceptorPoints: null,
                acceptedAt: null,
                place: 'Lake Lynn',
                comment: '',
                playedAt: dayjs.tz().add(2, 'day').add(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                createdAt: '2021-05-03 11:00:00',
                winner: null,
                score: null,
                same: '40,41',
                isProposalSent: 1,
            },
            {
                id: 41,
                initial: 1,
                challengerId: 5,
                acceptorId: null,
                challengerRank: 5,
                acceptorRank: null,
                challengerPoints: null,
                acceptorPoints: null,
                acceptedAt: null,
                place: 'Lake Lynn',
                comment: '',
                playedAt: dayjs.tz().add(2, 'day').add(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
                createdAt: '2021-05-03 11:00:00',
                winner: null,
                score: null,
                same: '40,41',
                isProposalSent: 1,
            },
            // Proposal accepted
            {
                id: 8,
                initial: 1,
                challengerId: 2,
                acceptorId: 1,
                challengerRank: 5,
                acceptorRank: 3,
                challengerPoints: null,
                acceptorPoints: null,
                place: 'Glen Eden',
                acceptedAt: '2021-05-03 17:50:47',
                playedAt: '2021-05-03 17:50:47',
                createdAt: '2021-05-04 09:00:00',
                winner: null,
                score: null,
                same: '',
                isProposalSent: 1,
            },
            {
                id: 9,
                initial: 1,
                challengerId: 1,
                acceptorId: 2,
                challengerRank: 5,
                acceptorRank: 3,
                challengerPoints: null,
                acceptorPoints: null,
                place: 'Winston',
                comment: 'Too late',
                acceptedAt: '2021-05-03 17:50:47',
                playedAt: dayjs.tz().add(6, 'day').format('YYYY-MM-DD HH:mm:ss'),
                createdAt: '2021-05-04 09:00:00',
                winner: null,
                score: null,
                same: '',
                isProposalSent: 1,
            },
            {
                id: 23,
                initial: 1,
                challengerId: 2,
                acceptorId: 6,
                challengerRank: 5,
                acceptorRank: 3,
                challengerPoints: null,
                acceptorPoints: null,
                place: 'Winston',
                acceptedAt: '2021-05-03 17:50:47',
                playedAt: dayjs.tz().format('YYYY-MM-DD HH:mm:ss'),
                createdAt: '2021-05-04 09:00:00',
                winner: null,
                score: null,
                same: '',
                isProposalSent: 1,
            },
        ],
        {}
    );
};

export const down = async ({ context: queryInterface }: { context: QueryInterface }) => {
    await queryInterface.bulkDelete('matches', {}, {});
};
