import IconHair from './hair.svg?react';
import IconGlasses from './glasses.svg?react';
import IconBeard from './beard.svg?react';
import IconCloth from './cloth.svg?react';
import IconEye from './eye.svg?react';
import IconEyebrow from './eyebrow.svg?react';
import IconMouth from './mouth.svg?react';
import IconFace from './face.svg?react';

export default {
    topType: {
        title: 'Hairstyle',
        tooltip: 'Select your hairstyle',
        icon: IconHair,
        options: [
            { value: 'CustomHair5', gender: 'male', rabbitWeight: 10 },
            { value: 'CustomHair6', gender: 'male' },
            { value: 'CustomHair7', gender: 'male' },
            { value: 'CustomHair8', gender: 'male', rabbitWeight: 10 },
            { value: 'NoHair', gender: 'male' },
            { value: 'ShortHairSides', gender: 'male' },
            { value: 'ShortHairTheCaesar', gender: 'male' },
            { value: 'ShortHairShortRound', gender: 'male' },
            { value: 'ShortHairShortFlat', gender: 'male', rabbitWeight: 10 },
            { value: 'ShortHairFrizzle', gender: 'male', rabbitWeight: 10 },
            { value: 'ShortHairDreads01', gender: 'male' },
            { value: 'ShortHairShortCurly', gender: 'male', rabbitWeight: 10 },
            { value: 'ShortHairShortWaved', gender: 'male' },
            { value: 'CustomHair3' },
            { value: 'CustomHair4' },
            { value: 'LongHairBun', gender: 'female' },
            { value: 'ShortHairShaggyMullet', gender: 'female' },
            { value: 'LongHairNotTooLong', gender: 'female', rabbitWeight: 10 },
            { value: 'CustomHair1' },
            { value: 'CustomHair2', rabbitWeight: 10 },
            { value: 'LongHairStraightStrand', gender: 'female', rabbitWeight: 10 },
            { value: 'LongHairStraight', gender: 'female', rabbitWeight: 10 },
            { value: 'LongHairStraight2', gender: 'female', rabbitWeight: 10 },
            { value: 'LongHairBob', gender: 'female', rabbitWeight: 10 },
            { value: 'LongHairMiaWallace', gender: 'female' },
            { value: 'LongHairCurly', gender: 'female' },
            { value: 'LongHairBigHair', gender: 'female' },
            { value: 'LongHairFro', gender: 'female' },
            { value: 'LongHairCurvy', gender: 'female' },
            { value: 'LongHairDreads' },
            { value: 'LongHairFrida', gender: 'female' },
            { value: 'Turban' },
            { value: 'WinterHat2' },
            { value: 'WinterHat3' },

            // { value: 'LongHairFroBand' },
            // { value: 'Eyepatch' }, // add to glasses section
            // { value: 'Hat' },
            // { value: 'Hijab' },
            // { value: 'LongHairShavedSides' },
            // { value: 'ShortHairDreads02' },
            // { value: 'ShortHairTheCaesarSidePart' },
            // { value: 'WinterHat1' },
            // { value: 'WinterHat4' },
        ],
    },
    hairColor: {
        title: 'Hair color',
        options: [
            { value: 'SilverGray' },
            { value: 'Platinum' },
            { value: 'BlondeGolden' },
            { value: 'Blonde' },
            { value: 'Auburn' },
            { value: 'Brown', weight: 3 },
            { value: 'BrownDark', weight: 3 },
            { value: 'Black' },
            { value: 'PastelPink' },
            { value: 'Red' },
            { value: 'PastelGreen' },
            { value: 'PastelOrange' },
            { value: 'Blue01' },
        ],
    },
    accessoriesType: {
        title: 'Glasses',
        tooltip: 'Add some glasses',
        icon: IconGlasses,
        options: [
            { value: 'Blank', weight: 5, rabbitWeight: 5 },
            { value: 'Kurt' },
            { value: 'Prescription01' },
            { value: 'Prescription02' },
            { value: 'Sunglasses' },
            { value: 'Wayfarers' },
            { value: 'CustomGlasses3' },
            { value: 'CustomGlasses4' },
            { value: 'CustomGlasses1' },
            { value: 'CustomGlasses2' },

            // { value: 'Round' }, // add
        ],
    },
    facialHairType: {
        title: 'Facial hair',
        tooltip: 'Choose your preferred facial hair.',
        icon: IconBeard,
        gender: 'male',
        options: [
            { value: 'Blank', weight: 3 },
            { value: 'MoustacheMagnum', gender: 'male' },
            { value: 'MoustacheFancy', gender: 'male' },
            { value: 'CustomMoustache1', gender: 'male' },
            { value: 'CustomMoustache2', gender: 'male' },
            { value: 'CustomMoustache3', gender: 'male' },
            { value: 'CustomMoustache4', gender: 'male' },
            { value: 'CustomMoustache5', gender: 'male' },
            { value: 'CustomMoustache6', gender: 'male' },
            { value: 'BeardLight', gender: 'male' },
            { value: 'BeardMedium', gender: 'male' },
            { value: 'BeardMajestic', gender: 'male' },
        ],
    },
    facialHairColor: {
        title: 'Beird color',
        options: [
            { value: 'SilverGray' },
            { value: 'Platinum' },
            { value: 'BlondeGolden' },
            { value: 'Blonde' },
            { value: 'Auburn' },
            { value: 'Brown', weight: 2, rabbitWeight: 3 },
            { value: 'BrownDark', weight: 2, rabbitWeight: 3 },
            { value: 'Black', weight: 2, rabbitWeight: 3 },
            { value: 'PastelPink' },
            { value: 'Red' },
            { value: 'PastelGreen' },
            { value: 'PastelOrange' },
            { value: 'Blue01' },
        ],
    },
    clotheType: {
        title: 'Clothing style',
        tooltip: 'Pick a clothing style.',
        icon: IconCloth,
        options: [
            { value: 'Overall' },
            { value: 'ShirtScoopNeck' },
            { value: 'ShirtVNeck' },
            { value: 'CollarSweater' },
            { value: 'ShirtCrewNeck' },
            { value: 'Hoodie' },
            { value: 'BlazerSweater' },

            // { value: 'BlazerShirt' },
            // { value: 'GraphicShirt' },
        ],
    },
    clotheColor: {
        title: 'Cloth color',
        options: [
            { value: 'Gray01' },
            { value: 'Gray02' },
            { value: 'Heather' },
            { value: 'Black', weight: 3 },
            { value: 'PastelBlue' },
            { value: 'Blue01' },
            { value: 'Blue02', weight: 3 },
            { value: 'Blue03' },
            { value: 'PastelYellow' },
            { value: 'TennisBall' },
            { value: 'PastelGreen' },
            { value: 'PastelOrange' },
            { value: 'Pink' },
            { value: 'Red', weight: 3 },

            // { value: 'White' },
        ],
    },
    eyeType: {
        title: 'Eyes',
        tooltip: 'Select your preferred eyes.',
        icon: IconEye,
        options: [
            { value: 'Default', weight: 3 },
            { value: 'Close' },
            { value: 'Happy', weight: 3 },
            { value: 'Wink' },
            { value: 'Side' },
            { value: 'Squint' },
            { value: 'EyeRoll' },
            { value: 'Surprised', weight: 3 },
            { value: 'Dizzy' },

            // { value: 'Cry' },
            // { value: 'Hearts' },
            // { value: 'WinkWacky' },
        ],
    },
    eyebrowType: {
        title: 'Eyebrows',
        tooltip: 'Pick some eyebrows',
        icon: IconEyebrow,
        options: [
            { value: 'Default', weight: 4 },
            { value: 'DefaultNatural' },
            { value: 'FlatNatural', weight: 3 },
            { value: 'RaisedExcited' },
            { value: 'UpDown', weight: 3 },
            { value: 'UnibrowNatural' },
            { value: 'AngryNatural' },

            // { value: 'Angry' },
            // { value: 'RaisedExcitedNatural' },
            // { value: 'SadConcerned' },
            // { value: 'SadConcernedNatural' },
            // { value: 'UpDownNatural' },
        ],
    },
    mouthType: {
        title: 'Mouth',
        tooltip: 'Choose a mouth',
        icon: IconMouth,
        options: [
            { value: 'Twinkle', weight: 4 },
            { value: 'Default', weight: 4 },
            { value: 'Smile', weight: 4 },
            { value: 'Tongue', weight: 2 },
            { value: 'Serious' },
            { value: 'Sad' },
            { value: 'Disbelief' },
            { value: 'Concerned' },
            { value: 'ScreamOpen' },
            { value: 'Eating' },
            { value: 'Grimace' },

            // { value: 'Vomit' },
        ],
    },
    skinColor: {
        title: 'Skin color',
        tooltip: 'Select a skin color.',
        icon: IconFace,
        options: [
            { value: 'Pale' },
            { value: 'Light', weight: 5 },
            { value: 'Brown' },
            { value: 'DarkBrown' },
            { value: 'Black' },

            // { value: 'Yellow' },
            // { value: 'Tanned' },
        ],
    },
};
